services:
  - type: web
    name: vibin-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vibin_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: vibin_backend.settings
      - key: SECRET_KEY
        value:  s
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
