services:
  - type: web
    name: vibin-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn vibin_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: vibin_backend.settings
      - key: SECRET_KEY
        value:  'django-insecure-!gpct4p0d5#2)f3!%6w_r5=z0g5s5f6=0_^5xuj@yd-05j5um3'
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
